## Quest

In [65]:
import pandas as pd

In [75]:
file_path = '../datasets/주식거래 수수료_20241217.xls'
compare_stock = pd.read_excel(file_path, header=2)
compare_stock

,회사명,수수료\n부과기준,기준일자,거래금액,구분,오프라인,HTS,ARS,스마트폰,오프라인.1,HTS.1,ARS.1,스마트폰.1,비고
0,유진투자증권,/img/sub/ico_xls.gif,2012/10/08,50만원,변경전,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.0,NaN
1,유진투자증권,/img/sub/ico_xls.gif,2020/06/17,50만원,변경후,2500.00000,900.0,1000.0,750.0,2500.0,75.0,1000.0,75.0,NaN
2,유진투자증권,/img/sub/ico_xls.gif,2020/06/17,50만원,변경율,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
3,SK증권,/img/sub/ico_xls.gif,2011/11/18,50만원,변경전,2500.00000,1750.0,1250.0,250.0,2500.0,75.0,1250.0,250.0,NaN
4,SK증권,/img/sub/ico_xls.gif,2015/06/01,50만원,변경후,2500.00000,1750.0,1250.0,1750.0,2500.0,75.0,1250.0,1750.0,증권통App 수수료율 변경
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,비엔피파리바증권,/img/sub/ico_pdf.gif,2020/02/03,50만원,변경율,-0.23077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,토스증권,/img/sub/ico_pdf.gif,2021/01/21,50만원,변경후,NaN,NaN,75.0,75.0,NaN,NaN,NaN,NaN,NaN
93,비엔케이투자증권,/img/sub/ico_pdf.gif,2016/12/05,50만원,변경전,NaN,NaN,NaN,750.0,NaN,NaN,NaN,750.0,NaN
94,비엔케이투자증권,/img/sub/ico_pdf.gif,2020/08/24,50만원,변경후,2246.00000,1496.0,NaN,750.0,2246.0,71.0,NaN,750.0,NaN
95,비엔케이투자증권,/img/sub/ico_pdf.gif,2020/08/24,50만원,변경율,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN

In [67]:
compare_stock_filter=compare_stock[compare_stock['구분']=='변경후']

In [68]:
compare_stock_filter[['회사명','HTS.1','스마트폰.1']]

          회사명   HTS.1  스마트폰.1
1      유진투자증권    75.0    75.0
4        SK증권    75.0  1750.0
7       유안타증권    70.0   500.0
10     신한투자증권     NaN     NaN
13       유화증권   390.0     NaN
16     미래에셋증권    70.0    70.0
18      상상인증권   700.0   700.0
20       대신증권  1536.0   986.0
23       교보증권  1240.0  1240.0
25     NH투자증권  1571.0  1486.0
27       한양증권  2236.0   500.0
30       신영증권   496.0   496.0
33       삼성증권  2236.0  2236.0
36      메리츠증권  1890.0  1890.0
39       KB증권    75.0   600.0
42     한화투자증권  2480.0   750.0
44      현대차증권  2291.0   991.0
46     DB금융투자  1246.0  1246.0
49      아이엠증권  1686.0  1686.0
51       부국증권   477.0   750.0
53     한국투자증권    70.0    70.0
56       하나증권    70.0    70.0
59     리딩투자증권   120.0     NaN
62       키움증권    70.0    70.0
65      엘에스증권    75.0    75.0
67      도이치증권     NaN     NaN
69  코리아에셋투자증권     NaN     NaN
72       흥국증권     NaN     NaN
75    IBK투자증권   500.0   500.0
78    케이프투자증권    75.0    75.0
81     DS투자증권     NaN     NaN
84     다올투자증권    70.0    70.0
87    카카오페이증권     NaN     NaN
90   비엔피파리바증권     NaN     NaN
92       토스증권     NaN     NaN
94   비엔케이투자증권    71.0   750.0

In [69]:
compare_stock_sum = compare_stock_filter[['HTS.1', '스마트폰.1']].sum(axis=1)
compare_stock_sum

1      150.0
4     1825.0
7      570.0
10       0.0
13     390.0
16     140.0
18    1400.0
20    2522.0
23    2480.0
25    3057.0
27    2736.0
30     992.0
33    4472.0
36    3780.0
39     675.0
42    3230.0
44    3282.0
46    2492.0
49    3372.0
51    1227.0
53     140.0
56     140.0
59     120.0
62     140.0
65     150.0
67       0.0
69       0.0
72       0.0
75    1000.0
78     150.0
81       0.0
84     140.0
87       0.0
90       0.0
92       0.0
94     821.0
dtype: float64

In [70]:
compare_stock_filter['HTS1+스마트폰1']=compare_stock_sum
compare_stock_filter

/tmp/ipykernel_73377/3016505109.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  compare_stock_filter['HTS1+스마트폰1']=compare_stock_sum

,회사명,수수료\n부과기준,기준일자,거래금액,구분,오프라인,HTS,ARS,스마트폰,오프라인.1,HTS.1,ARS.1,스마트폰.1,비고,HTS1+스마트폰1
1,유진투자증권,/img/sub/ico_xls.gif,2020/06/17,50만원,변경후,2500.0,900.0,1000.0,750.0,2500.0,75.0,1000.0,75.0,NaN,150.0
4,SK증권,/img/sub/ico_xls.gif,2015/06/01,50만원,변경후,2500.0,1750.0,1250.0,1750.0,2500.0,75.0,1250.0,1750.0,증권통App 수수료율 변경,1825.0
7,유안타증권,/img/sub/ico_pdf.gif,2021/01/04,50만원,변경후,2500.0,1750.0,985.0,500.0,2500.0,70.0,985.0,500.0,NaN,570.0
10,신한투자증권,/img/sub/ico_pdf.gif,2015/04/01,50만원,변경후,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
13,유화증권,/img/sub/ico_pdf.gif,2012/05/02,50만원,변경후,2490.0,390.0,1240.0,NaN,2490.0,390.0,1240.0,NaN,증권유관기관 수수료인하('12.5.2)부분 반영,390.0
16,미래에셋증권,/img/sub/ico_pdf.gif,2017/01/02,50만원,변경후,2450.0,700.0,700.0,700.0,2450.0,70.0,70.0,70.0,NaN,140.0
18,상상인증권,/img/sub/ico_pdf.gif,2020/04/23,50만원,변경후,2450.0,700.0,1000.0,700.0,2450.0,700.0,1000.0,700.0,NaN,1400.0
20,대신증권,/img/sub/ico_pdf.gif,2021/01/01,50만원,변경후,2486.0,1536.0,986.0,986.0,2486.0,1536.0,986.0,986.0,NaN,2522.0
23,교보증권,/img/sub/ico_pdf.gif,2021/09/01,50만원,변경후,2490.0,1240.0,1240.0,1240.0,2490.0,1240.0,1240.0,1240.0,NaN,2480.0
25,NH투자증권,/img/sub/ico_pdf.gif,2020/06/10,50만원,변경후,2486.0,1571.0,1486.0,1486.0,2486.0,1571.0,1486.0,1486.0,NAMUH 50,3057.0
27,한양증권,/img/sub/ico_hwp.gif,2012/10/12,50만원,변경후,2487.0,2236.0,996.0,500.0,2487.0,2236.0,996.0,500.0,NaN,2736.0
30,신영증권,/img/sub/ico_hwp.gif,2021/08/23,50만원,변경후,2246.0,496.0,1246.0,496.0,2246.0,496.0,1246.0,496.0,NaN,992.0
33,삼성증권,/img/sub/ico_pdf.gif,2021/10/01,50만원,변경후,2486.0,2236.0,1236.0,2236.0,2486.0,2236.0,1236.0,2236.0,NaN,4472.0
36,메리츠증권,/img/sub/ico_pdf.gif,2021/01/01,50만원,변경후,2490.0,1890.0,990.0,1890.0,2490.0,1890.0,990.0,1890.0,NaN,3780.0
39,KB증권,/img/sub/ico_pdf.gif,2021/11/25,50만원,변경후,2487.0,1786.0,1237.0,987.0,2487.0,75.0,750.0,600.0,NaN,675.0
42,한화투자증권,/img/sub/ico_pdf.gif,2016/05/30,50만원,변경후,2480.0,2480.0,980.0,750.0,2480.0,2480.0,980.0,750.0,NaN,3230.0
44,현대차증권,/img/sub/ico_xlsx.gif,2011/11/07,50만원,변경후,2491.0,2291.0,1241.0,991.0,2491.0,2291.0,1241.0,991.0,NaN,3282.0
46,DB금융투자,/img/sub/ico_doc.gif,2015/01/02,50만원,변경후,2496.0,1246.0,1246.0,1246.0,2496.0,1246.0,1246.0,1246.0,NaN,2492.0
49,아이엠증권,/img/sub/ico_hwp.gif,2012/05/02,50만원,변경후,2486.0,1686.0,1236.0,1686.0,2486.0,1686.0,1236.0,1686.0,유관수수료인하,3372.0
51,부국증권,/img/sub/ico_hwp.gif,2011/11/18,50만원,변경후,2227.0,477.0,977.0,750.0,2227.0,477.0,977.0,750.0,NaN,1227.0
53,한국투자증권,/img/sub/ico_pdf.gif,2021/11/25,50만원,변경후,2486.0,2636.0,1236.0,2636.0,NaN,70.0,1236.0,70.0,코스피/코스닥/장외단주/코넥스,140.0
56,하나증권,/img/sub/ico_pdf.gif,2014/09/01,50만원,변경후,2480.0,2480.0,2480.0,2480.0,2480.0,70.0,70.0,70.0,NaN,140.0
59,리딩투자증권,/img/sub/ico_pdf.gif,2014/07/14,50만원,변경후,2500.0,120.0,700.0,NaN,2500.0,120.0,700.0,NaN,NaN,120.0
62,키움증권,/img/sub/ico_pdf.gif,2020/12/31,50만원,변경후,1500.0,70.0,750.0,70.0,1500.0,70.0,750.0,70.0,NaN,140.0
65,엘에스증권,/img/sub/ico_pdf.gif,2012/12/03,50만원,변경후,2400.0,75.0,500.0,75.0,1500.0,75.0,500.0,75.0,거래금액 5천만원 미만 : 0.48%\n거래금액 5천~3억 미만 : 0.45%\n거...,150.0
67,도이치증권,/img/sub/ico_pdf.gif,2014/12/17,50만원,변경후,2000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
69,코리아에셋투자증권,/img/sub/ico_pdf.gif,2019/04/10,50만원,변경후,500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
72,흥국증권,/img/sub/ico_pdf.gif,2012/06/01,50만원,변경후,2450.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
75,IBK투자증권,/img/sub/ico_hwp.gif,2013/02/04,50만원,변경후,2500.0,500.0,1250.0,500.0,2500.0,500.0,1250.0,500.0,NaN,1000.0
78,케이프투자증권,/img/sub/ico_doc.gif,2015/04/20,50만원,변경후,3750.0,2500.0,NaN,450.0,3750.0,75.0,NaN,75.0,1. 고객등급 실버등급은 당일 종목당 매수/매도 매체별 합산 하여 50만원 미만시 ...,150.0
81,DS투자증권,/img/sub/ico_hwp.gif,2021/01/01,50만원,변경후,2478.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
84,다올투자증권,/img/sub/ico_pdf.gif,2018/03/12,50만원,변경후,2490.0,70.0,750.0,70.0,2490.0,70.0,750.0,70.0,NaN,140.0
87,카카오페이증권,/img/sub/ico_pdf.gif,2024/10/14,50만원,변경후,2500.0,NaN,75.0,75.0,NaN,NaN,NaN,NaN,NaN,0.0
90,비엔피파리바증권,/img/sub/ico_pdf.gif,2020/02/03,50만원,변경후,1500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
92,토스증권,/img/sub/ico_pdf.gif,2021/01/21,50만원,변경후,NaN,NaN,75.0,75.0,NaN,NaN,NaN,NaN,NaN,0.0
94,비엔케이투자증권,/img/sub/ico_pdf.gif,2020/08/24,50만원,변경후,2246.0,1496.0,NaN,750.0,2246.0,71.0,NaN,750.0,NaN,821.0

In [71]:
new_compare_stock = compare_stock_filter.sort_values(by=['HTS1+스마트폰1'], ascending=[True])

In [72]:
new_compare_stock_list = new_compare_stock[['회사명','HTS1+스마트폰1']]
new_compare_stock_list

          회사명  HTS1+스마트폰1
10     신한투자증권         0.0
69  코리아에셋투자증권         0.0
72       흥국증권         0.0
81     DS투자증권         0.0
67      도이치증권         0.0
92       토스증권         0.0
90   비엔피파리바증권         0.0
87    카카오페이증권         0.0
59     리딩투자증권       120.0
56       하나증권       140.0
84     다올투자증권       140.0
16     미래에셋증권       140.0
62       키움증권       140.0
53     한국투자증권       140.0
65      엘에스증권       150.0
1      유진투자증권       150.0
78    케이프투자증권       150.0
13       유화증권       390.0
7       유안타증권       570.0
39       KB증권       675.0
94   비엔케이투자증권       821.0
30       신영증권       992.0
75    IBK투자증권      1000.0
51       부국증권      1227.0
18      상상인증권      1400.0
4        SK증권      1825.0
23       교보증권      2480.0
46     DB금융투자      2492.0
20       대신증권      2522.0
27       한양증권      2736.0
25     NH투자증권      3057.0
42     한화투자증권      3230.0
44      현대차증권      3282.0
49      아이엠증권      3372.0
36      메리츠증권      3780.0
33       삼성증권      4472.0

In [73]:
new_compare_stock_list.iloc[ :5, :]

          회사명  HTS1+스마트폰1
10     신한투자증권         0.0
69  코리아에셋투자증권         0.0
72       흥국증권         0.0
81     DS투자증권         0.0
67      도이치증권         0.0